name: LOC Count

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Count lines of code (excluding JSON)
        id: cloc
        run: |
          cloc . --exclude-dir=.github,.git --exclude-ext=json --md > cloc-report.md
          echo "## 📊 Lines of Code Report (excluding JSON)" >> $GITHUB_STEP_SUMMARY
          cat cloc-report.md >> $GITHUB_STEP_SUMMARY

      - name: Post LOC report as PR comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          header: "📊 Lines of Code Report (excluding JSON)"
          body: |
            ```markdown
            ${{ steps.cloc.outputs.stdout }}
            ```
